// Downloads the site's icons from Material Symbols (Google, Apache License 2.0,
// https://github.com/google/material-design-icons) through the Iconify API and writes src/data/icons.ts.
// Same icon family as the RONDA app (Flutter Material Icons). Rounded style, 24 x 24.
//
//   node scripts/fetch-icons.mjs
//
// To add an icon: find it on https://icon-sets.iconify.design/material-symbols/ , add its name below, rerun.
import fs from 'node:fs'

const NAMES = [
  // arrows and controls
  'chevron-left-rounded', 'chevron-right-rounded', 'expand-more-rounded', 'expand-less-rounded',
  'close-rounded', 'check-rounded', 'search-rounded', 'search-off-rounded', 'swap-vert-rounded', 'edit-outline-rounded',
  // header, time, notices
  'help-outline-rounded', 'person-outline-rounded', 'language-rounded', 'calendar-month-outline-rounded',
  'schedule-outline-rounded', 'dark-mode-outline-rounded', 'star-rounded', 'info-outline-rounded', 'description-outline-rounded',
  // travel
  'directions-walk-rounded', 'accessible-rounded', 'train-outline-rounded', 'directions-bus-outline-rounded', 'flight-rounded',
  'route-outline-rounded', 'map-outline-rounded', 'hiking-rounded', 'translate-rounded', 'adjust-rounded',
  'bookmark-outline-rounded', 'notifications-outline-rounded',
  // money
  'payments-outline-rounded', 'credit-card-outline-rounded', 'currency-exchange-rounded',
  // places
  'location-on-outline-rounded', 'local-hospital-outline-rounded', 'school-outline-rounded', 'shopping-bag-outline-rounded',
  'mosque-outline-rounded', 'home-outline-rounded', 'apartment-rounded', 'restaurant-rounded',
  'account-balance-outline-rounded', 'park-outline-rounded',
  // two-tone feature icons (filled main shape + small accent)
  'route-rounded', 'location-on-rounded', 'train-rounded', 'payments-rounded', 'my-location-rounded', 'bookmark-rounded',
  'notifications-rounded', 'palette-rounded', 'sell-rounded', 'map-rounded', 'luggage-rounded', 'chat-rounded',
  'storefront-rounded', 'favorite-rounded',
  // services
  'directions-car-rounded', 'airport-shuttle-rounded', 'event-rounded', 'flight-land-rounded', 'badge-rounded',
]

const res = await fetch(`https://api.iconify.design/material-symbols.json?icons=${NAMES.join(',')}`)
if (!res.ok) throw new Error(`Iconify ${res.status}`)
const set = await res.json()
if (set.not_found?.length) throw new Error(`not found: ${set.not_found.join(', ')}`)

// an alias points at another icon, sometimes flipped / rotated
const body = (name) => {
  if (set.icons[name]) return set.icons[name].body
  const a = set.aliases?.[name]
  if (!a) throw new Error(`missing ${name}`)
  let b = body(a.parent)
  const t = []
  if (a.hFlip) t.push('translate(24 0) scale(-1 1)')
  if (a.vFlip) t.push('translate(0 24) scale(1 -1)')
  if (a.rotate) t.push(`rotate(${a.rotate * 90} 12 12)`)
  if (t.length) b = `<g transform="${t.join(' ')}">${b}</g>`
  return b
}

const camel = (n) => n.replace(/-rounded$/, '').replace(/-([a-z])/g, (_, c) => c.toUpperCase())
const lines = NAMES.map((n) => `  ${camel(n)}: ${JSON.stringify(body(n))},`)
const out = `// Generated by scripts/fetch-icons.mjs. Do not edit by hand.
// Material Symbols Rounded (Google), Apache License 2.0: https://github.com/google/material-design-icons
// SVG bodies for a 24 x 24 viewBox, fill = currentColor.
export const ICONS = {
${lines.join('\n')}
} as const

export type IconName = keyof typeof ICONS
`
fs.writeFileSync(new URL('../src/data/icons.ts', import.meta.url), out)
console.log(`${NAMES.length} icons -> src/data/icons.ts`)
